{{- if and .Values.admin.enabled .Values.admin.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retraced.adminCredentialsSecretName" . }}
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
stringData:
  JACKSON_API_KEYS: {{ .Values.admin.credentials.jacksonApiKeys | quote }}
  DB_URL: {{ .Values.admin.credentials.dbUrl | quote }}
  NEXTAUTH_SECRET: {{ .Values.admin.credentials.nextauthSecret | quote }}
  RETRACED_ADMIN_ROOT_TOKEN: {{ .Values.admin.credentials.retracedAdminRootToken | quote }}
  SMTP_HOST: {{ .Values.admin.credentials.smtpHost | quote }}
  SMTP_PORT: {{ .Values.admin.credentials.smtpPort | quote }}
  SMTP_USER: {{ .Values.admin.credentials.smtpUser | quote }}
  SMTP_PASSWORD: {{ .Values.admin.credentials.smtpPassword | quote }}
  SMTP_FROM: {{ .Values.admin.credentials.smtpFrom | quote }}
{{- end }}
