apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-api-internal
  labels:
    app: auditlog-internal
    retraceddev: "1"
    tier: api
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiInternal.type }}
  selector:
    app: auditlog
    retraceddev: "1"
    tier: api
  {{- include "retraced.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.apiInternal.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-api
  labels:
    app: auditlog
    retraceddev: "1"
    tier: api
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: auditlog
    retraceddev: "1"
    tier: api
  {{- include "retraced.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 }}
