apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-api-internal
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.internalService.type }}
  selector:
    {{- include "retraced.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.internalService.port }}
      targetPort: http
      protocol: TCP
