{{- if not .Values.auditlog.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retraced.fullname" . }}-auditlog
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: auditlog-secret
stringData:
  ADMIN_ROOT_TOKEN: {{ required "auditlog.adminRootToken is required" .Values.auditlog.adminRootToken | quote }}
  API_BASE_URL_PATH: {{ required "auditlog.apiBaseUrlPath is required" .Values.auditlog.apiBaseUrlPath | quote }}
  API_TOKEN: {{ .Values.auditlog.apiToken | quote }}
  DB_TOKEN: {{ .Values.auditlog.dbToken | quote }}
  ELASTICSEARCH_NODES: {{ required "auditlog.elasticsearchNodes is required" .Values.auditlog.elasticsearchNodes | quote }}
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.auditlog.geoipupdateAccountId | quote }}
  GEOIPUPDATE_DB_DIR: {{ required "auditlog.geoipupdateDbDir is required" .Values.auditlog.geoipupdateDbDir | quote }}
  GEOIPUPDATE_EDITION_IDS: {{ required "auditlog.geoipupdateEditionIds is required" .Values.auditlog.geoipupdateEditionIds | quote }}
  GEOIPUPDATE_FREQUENCY: {{ required "auditlog.geoipupdateFrequency is required" .Values.auditlog.geoipupdateFrequency | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.auditlog.geoipupdateLicenseKey | quote }}
  GEOIPUPDATE_USE_MMDB: {{ .Values.auditlog.geoipupdateUseMmdb | quote }}
  GEOIPUPDATE_VERBOSE: {{ required "auditlog.geoipupdateVerbose is required" .Values.auditlog.geoipupdateVerbose | quote }}
  HMAC_SECRET_ADMIN: {{ required "auditlog.hmacSecretAdmin is required" .Values.auditlog.hmacSecretAdmin | quote }}
  HMAC_SECRET_VIEWER: {{ required "auditlog.hmacSecretViewer is required" .Values.auditlog.hmacSecretViewer | quote }}
  LOG_LEVEL: {{ required "auditlog.logLevel is required" .Values.auditlog.logLevel | quote }}
  MANDRILL_KEY: {{ .Values.auditlog.mandrillKey | quote }}
  NSQD_HOST: {{ required "auditlog.nsqdHost is required" .Values.auditlog.nsqdHost | quote }}
  NSQD_HTTP_PORT: {{ required "auditlog.nsqdHttpPort is required" .Values.auditlog.nsqdHttpPort | quote }}
  NSQD_TCP_PORT: {{ required "auditlog.nsqdTcpPort is required" .Values.auditlog.nsqdTcpPort | quote }}
  POSTGRES_DATABASE: {{ required "auditlog.postgresDatabase is required" .Values.auditlog.postgresDatabase | quote }}
  POSTGRES_HOST: {{ required "auditlog.postgresHost is required" .Values.auditlog.postgresHost | quote }}
  POSTGRES_PASSWORD: {{ required "auditlog.postgresPassword is required" .Values.auditlog.postgresPassword | quote }}
  POSTGRES_POOL_SIZE: {{ required "auditlog.postgresPoolSize is required" .Values.auditlog.postgresPoolSize | quote }}
  POSTGRES_PORT: {{ required "auditlog.postgresPort is required" .Values.auditlog.postgresPort | quote }}
  POSTGRES_USER: {{ required "auditlog.postgresUser is required" .Values.auditlog.postgresUser | quote }}
  PROCESSOR_TOKEN: {{ .Values.auditlog.processorToken | quote }}
  RETRACED_API_BASE: {{ required "auditlog.retracedApiBase is required" .Values.auditlog.retracedApiBase | quote }}
  RETRACED_DISABLE_GEOSYNC: {{ .Values.auditlog.retracedDisableGeosync | quote }}
  STAGE: {{ .Values.auditlog.stage | quote }}
  STATSD_HOST: {{ .Values.auditlog.statsdHost | quote }}
  STATSD_PORT: {{ .Values.auditlog.statsdPort | quote }}
{{- end }}
