{{- if .Values.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retraced.fullname" . }}-credentials
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials
stringData:
  ADMIN_ROOT_TOKEN: {{ .Values.credentials.adminRootToken | quote }}
  API_TOKEN: {{ .Values.credentials.apiToken | quote }}
  DB_TOKEN: {{ .Values.credentials.dbToken | quote }}
  PROCESSOR_TOKEN: {{ .Values.credentials.processorToken | quote }}
  MANDRILL_KEY: {{ .Values.credentials.mandrillKey | quote }}
  HMAC_SECRET_ADMIN: {{ .Values.hmac.secretAdmin | quote }}
  HMAC_SECRET_VIEWER: {{ .Values.hmac.secretViewer | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.accountId | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.licenseKey | quote }}
  ELASTICSEARCH_NODES: {{ .Values.elasticsearch.nodes | quote }}
{{- end }}
