apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-cron
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  replicas: {{ .Values.cron.replicaCount }}
  selector:
    matchLabels:
      {{- include "retraced.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cron
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cron
    spec:
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      containers:
        - name: cron
          image: {{ .Values.cron.image.repository }}:{{ .Values.cron.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.cron.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - /usr/local/bin/retraced-auditlog-cron /crontab 2>&1 | grep ERRO
          env:
            - name: NSQD_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: NSQD_HOST
            - name: NSQD_HTTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: NSQD_HTTP_PORT
            - name: RETRACED_DISABLE_GEOSYNC
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: RETRACED_DISABLE_GEOSYNC
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          resources: {{- toYaml .Values.cron.resources | nindent 12 }}
