apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-cron
  labels:
    retraceddev: "1"
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cron.replicas }}
  selector:
    matchLabels:
      retraceddev: "1"
      tier: cron
    {{- include "retraced.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: auditlog
        dest: nsq
        retraceddev: "1"
        source: cron
        tier: cron
      {{- include "retraced.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /usr/local/bin/retraced-auditlog-cron /crontab 2>&1 | grep ERRO
        env:
        - name: NSQD_HOST
          valueFrom:
            secretKeyRef:
              key: NSQD_HOST
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: NSQD_HTTP_PORT
          valueFrom:
            secretKeyRef:
              key: NSQD_HTTP_PORT
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: RETRACED_DISABLE_GEOSYNC
          valueFrom:
            secretKeyRef:
              key: RETRACED_DISABLE_GEOSYNC
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.cron.cron.image.repository }}:{{ .Values.cron.cron.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.cron.cron.imagePullPolicy }}
        name: cron
        resources: {{- toYaml .Values.cron.cron.resources | nindent 10 }}
