apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-dbutil
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: dbutil
spec:
  replicas: {{ .Values.dbutil.replicaCount }}
  selector:
    matchLabels:
      {{- include "retraced.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dbutil
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dbutil
    spec:
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      containers:
        - name: dbutil
          image: {{ .Values.dbutil.image.repository }}:{{ .Values.dbutil.image.tag | default .Chart.AppVersion }}
          command:
            - /bin/sleep
            - infinity
          env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - secretRef:
                name: {{ include "retraced.auditlogSecretName" . }}
          resources: {}
