{{- if .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "retraced.fullname" . }}-migrate-es
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate-es
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate-es
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      containers:
        - name: db
          image: {{ include "retraced.image" (dict "image" .Values.migrateEs.image "global" .Values.global "default" .Chart.AppVersion) }}
          command:
            - node
            - build/src/_db/runner-lite.js
            - es
          envFrom: {{- include "retraced.envFrom" . | nindent 12 }}
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.credentialsSecretName" . }}
                  key: DB_TOKEN
            - name: SCHEMA_PATH
              value: {{ quote .Values.migrateEs.env.schemaPath }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources: {}
{{- end }}
