{{- if .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "retraced.fullname" . }}-migrate-es
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate-es
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate-es
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      containers:
        - name: db
          image: {{ .Values.migrateEs.image.repository }}:{{ .Values.migrateEs.image.tag | default .Chart.AppVersion }}
          command:
            - node
            - build/src/_db/runner-lite.js
            - es
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: DB_TOKEN
            - name: SCHEMA_PATH
              value: {{ quote .Values.migrateEs.env.schemaPath }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - secretRef:
                name: {{ include "retraced.auditlogSecretName" . }}
          resources: {}
{{- end }}
