apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "retraced.fullname" . }}-migrate-es
  labels:
    retraceddev: "1"
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        retraceddev: "1"
    spec:
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - build/src/_db/runner-lite.js
        - es
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: DB_TOKEN
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: SCHEMA_PATH
          value: {{ quote .Values.migrateEs.db.env.schemaPath }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: {{ include "retraced.auditlogSecretName" . }}
        image: {{ .Values.migrateEs.db.image.repository }}:{{ .Values.migrateEs.db.image.tag
          | default .Chart.AppVersion }}
        name: db
        resources: {}
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 0
