apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-nsqd
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: nsqd
spec:
  replicas: {{ .Values.nsqd.replicaCount }}
  selector:
    matchLabels:
      {{- include "retraced.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nsqd
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nsqd
    spec:
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      containers:
        - name: nsqd
          image: {{ .Values.nsqd.image.repository }}:{{ .Values.nsqd.image.tag | default .Chart.AppVersion }}
          command:
            - /bin/sh
          args: {{- toYaml .Values.nsqd.args | nindent 12 }}
          env:
            - name: STATSD_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: STATSD_HOST
            - name: STATSD_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.auditlogSecretName" . }}
                  key: STATSD_PORT
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          ports:
            - name: tcp
              containerPort: 4150
              protocol: TCP
            - name: http
              containerPort: 4151
              protocol: TCP
          resources: {{- toYaml .Values.nsqd.resources | nindent 12 }}
