apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-nsqd
  labels:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nsqd.type }}
  selector:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  {{- include "retraced.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nsqd.ports | toYaml | nindent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-nsqd
  labels:
    retraceddev: "1"
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nsqd.replicas }}
  selector:
    matchLabels:
      retraceddev: "1"
      tier: nsq
    {{- include "retraced.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: auditlog
        retraceddev: "1"
        tier: nsq
      {{- include "retraced.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.nsqd.nsqd.args | nindent 8 }}
        command:
        - /bin/sh
        env:
        - name: STATSD_HOST
          valueFrom:
            secretKeyRef:
              key: STATSD_HOST
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: STATSD_PORT
          valueFrom:
            secretKeyRef:
              key: STATSD_PORT
              name: {{ include "retraced.auditlogSecretName" . }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nsqd.nsqd.image.repository }}:{{ .Values.nsqd.nsqd.image.tag
          | default .Chart.AppVersion }}
        name: nsqd
        ports:
        - containerPort: 4150
        - containerPort: 4151
        resources: {{- toYaml .Values.nsqd.nsqd.resources | nindent 10 }}
