apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-processor
  labels:
    retraceddev: "1"
  {{- include "retraced.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processor.replicas }}
  selector:
    matchLabels:
      retraceddev: "1"
      tier: processor
    {{- include "retraced.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: auditlog
        retraceddev: "1"
        tier: processor
      {{- include "retraced.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - auditlog
                - key: tier
                  operator: In
                  values:
                  - processor
              topologyKey: kubernetes.io/hostname
            weight: 2
      containers:
      - command:
        - node
        - --inspect=0.0.0.0
        - build/src/_processor/index.js
        env:
        - name: TMPDIR
          value: {{ quote .Values.processor.processor.env.tmpdir }}
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              key: PROCESSOR_TOKEN
              name: {{ include "retraced.fullname" . }}-auditlog
        - name: PG_SEARCH
          value: {{ quote .Values.processor.processor.env.pgSearch }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: {{ include "retraced.fullname" . }}-auditlog
        image: {{ .Values.processor.processor.image.repository }}:{{ .Values.processor.processor.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.processor.processor.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /livez
            port: 3000
          periodSeconds: 60
        name: processor
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          successThreshold: 2
          timeoutSeconds: 10
        resources: {{- toYaml .Values.processor.processor.resources | nindent 10 }}
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmpdir
      volumes:
      - emptyDir: {}
        name: tmpdir
