apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retraced.fullname" . }}-processor
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  replicas: {{ .Values.processor.replicas }}
  selector:
    matchLabels:
      {{- include "retraced.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: processor
  template:
    metadata:
      labels:
        {{- include "retraced.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: processor
    spec:
      serviceAccountName: {{ include "retraced.serviceAccountName" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "retraced.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: processor
      containers:
        - name: processor
          image: {{ include "retraced.image" (dict "image" .Values.processor.image "global" .Values.global "default" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.processor.image.pullPolicy }}
          command:
            - node
            - build/src/_processor/index.js
          envFrom: {{- include "retraced.envFrom" . | nindent 12 }}
          env:
            - name: TMPDIR
              value: {{ quote .Values.processor.env.tmpdir }}
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "retraced.credentialsSecretName" . }}
                  key: PROCESSOR_TOKEN
            - name: PG_SEARCH
              value: {{ if not .Values.elasticsearch.enabled }}"TRUE"{{ else }}""{{ end }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 5
            periodSeconds: 30
            successThreshold: 2
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            failureThreshold: 5
            periodSeconds: 60
          resources: {{- toYaml .Values.processor.resources | nindent 12 }}
          volumeMounts:
            - name: tmpdir
              mountPath: /tmp
      volumes:
        - name: tmpdir
          emptyDir: {}
